icons_format = "{icon}"

[theme]
theme = "ctp-macchiato"
[theme.overrides]
idle_bg = "#24273a"
idle_fg = "#abcdef"
separator = " "
[icons]
icons = "awesome4"
[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $prev $play $next |}"
[[block]]
block = "cpu"
[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $used.eng(w:2) "
[[block]]
block = "battery"
device = "BAT1"
[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %I:%M %p')"
[[block]]
block = "custom"
command="echo  "
[[block.click]]
button = "left"
cmd = "kill -s USR1 $(pidof deadd-notification-center)"
