# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "alcor"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/84efd03d-cd35-48a4-91bb-8a1a854d7112";
    fsType = "btrfs";
    options = ["subvol=@"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/84efd03d-cd35-48a4-91bb-8a1a854d7112";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };
  fileSystems."/homeSnaps" = {
    device = "/dev/disk/by-uuid/84efd03d-cd35-48a4-91bb-8a1a854d7112";
    fsType = "btrfs";
    options = ["subvol=@home_snaps"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/750D-3BB8";
    fsType = "vfat";
  };
  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/d827308c-517a-4955-a0ff-ec1b9b9d7c67";
    fsType = "btrfs";
    options = ["subvol=@data"];
  };
  fileSystems."/dataSnaps" = {
    device = "/dev/disk/by-uuid/d827308c-517a-4955-a0ff-ec1b9b9d7c67";
    fsType = "btrfs";
    options = ["subvol=@data_snapshots"];
  };

  fileSystems."/nocow" = {
    device = "/dev/disk/by-uuid/d827308c-517a-4955-a0ff-ec1b9b9d7c67";
    fsType = "btrfs";
    options = ["subvol=@nocow,nodatacow"];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/627c4eab-2d00-4464-b515-09c7bda0f618";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  systemd.tmpfiles.rules = (
    lib.mapAttrsToList (n: v: "w /sys/module/zswap/parameters/${n}  - - - - ${toString v}") {
      enabled = true;

      # I think with swap, you need speed first and foremost and compression
      # efficiency is secondary. OTOH, in my testing, zstd is able to store
      # the first 3 pages of random files in my closure in 1 page ~40% of
      # the time vs. only ~10% with lz4 although the bulk is 2 pages in
      # either case. I consider zswap as a best-effort speed efficiency
      # boost though, so speed is more important I think.
      compressor = "lz4";

      # AFAIK zsmalloc has memory fragmentation issues because it concatenates
      # compressed pages with no regard for page boundaries. Reading a single
      # page from compressed memory might require reading many pages. z3fold
      # does not have such issues and a 3:1 compression ratio is good enough for
      # me; the same point about me merely considering zswap an efficiency
      # booster applies here.
      zpool = "z3fold";

      # This controls how much of the system RAM may be taken up by swap. On the
      # one hand, you might think one wants this as high as possible but you
      # must consider that at some point you do actually want stuff to be
      # swapped out to disk as zswap is merely a stage between memory and swap
      # that is cheaper than actual swap in terms of performance but still
      # requires memory; memory that is still taken away from file-backed pages.
      # Let's keep the default limit of 20% until I have formed a better opinion
      # on this.
      # max_pool_percent = "20";
    }
  );
}
