#!/bin/bash

# Get the number of connected monitors using xrandr
num_monitors=$(xrandr | grep " connected" | wc -l)

# If there's more than one monitor, disable the built-in monitor
if [ $num_monitors -gt 1 ]; then
    # Get the name of the built-in monitor using xrandr
    #inbuilt_monitor=$(xrandr | grep " connected primary" | cut -d " " -f 1)
    inbuilt_monitor="eDP-1-1"
    # Turn off the built-in monitor
    xrandr --output $inbuilt_monitor --off
#xrandr --output HDMI-0 --auto --output eDP-1-1 --auto --left-of HDMI-0
    # Wait for a few seconds to ensure the monitor has been turned off
#    sleep 5

    # Turn on the built-in monitor again
#    xrandr --output $inbuilt_monitor --auto
fi

